CREATE TABLE movies (
  id INT PRIMARY KEY,
  title VARCHAR(255),
  year INT,
  director VARCHAR(255),
  genre VARCHAR(255),
  rating DECIMAL(3,1)
);

INSERT INTO movies (id, title, year, director, genre, rating)
VALUES
  (1, 'The Shawshank Redemption', 1994, 'Frank Darabont', 'Drama', 9.3),
  (2, 'The Godfather', 1972, 'Francis Ford Coppola', 'Crime, Drama', 9.2),
  (3, 'Pulp Fiction', 1994, 'Quentin Tarantino', 'Crime, Drama', 8.9),
  (4, 'The Dark Knight', 2008, 'Christopher Nolan', 'Action, Crime, Drama', 9.0),
  (5, 'Fight Club', 1999, 'David Fincher', 'Drama', 8.8),
  (6, 'Inception', 2010, 'Christopher Nolan', 'Action, Adventure, Sci-Fi', 8.8),
  (7, 'Forrest Gump', 1994, 'Robert Zemeckis', 'Drama, Romance', 8.8),
  (8, 'The Matrix', 1999, 'The Wachowski Brothers', 'Action, Sci-Fi', 8.7),
  (9, 'The Lord of the Rings: The Fellowship of the Ring', 2001, 'Peter Jackson', 'Adventure, Drama, Fantasy', 8.8),
  (10, 'Avengers: Endgame', 2019, 'Anthony Russo, Joe Russo', 'Action, Adventure, Sci-Fi', 8.4);

INSERT INTO movies (id, title, year, director, genre, rating)
VALUES
  (11, 'Schindler''s List', 1993, 'Steven Spielberg', 'Biography, Drama, History', 8.9),
  (12, 'The Lord of the Rings: The Two Towers', 2002, 'Peter Jackson', 'Adventure, Drama, Fantasy', 8.7),
  (13, 'The Godfather: Part II', 1974, 'Francis Ford Coppola', 'Crime, Drama', 9.0),
  (14, 'The Shawshank Redemption', 1994, 'Frank Darabont', 'Drama', 9.3),
  (15, 'The Dark Knight Rises', 2012, 'Christopher Nolan', 'Action, Thriller', 8.4),
  (16, 'Goodfellas', 1990, 'Martin Scorsese', 'Biography, Crime, Drama', 8.7),
  (17, 'The Avengers', 2012, 'Joss Whedon', 'Action, Adventure, Sci-Fi', 8.0),
  (18, 'Interstellar', 2014, 'Christopher Nolan', 'Adventure, Drama, Sci-Fi', 8.6),
  (19, 'Whiplash', 2014, 'Damien Chazelle', 'Drama, Music', 8.5),
  (20, 'Gone with the Wind', 1939, 'Victor Fleming', 'Drama, History, Romance', 8.1);

INSERT INTO movies (id, title, year, director, genre, rating)
VALUES
  (21, 'The Lion King', 1994, 'Roger Allers, Rob Minkoff', 'Animation, Adventure, Drama', 8.5),
  (22, 'Casablanca', 1942, 'Michael Curtiz', 'Drama, Romance, War', 8.5),
  (23, 'The Silence of the Lambs', 1991, 'Jonathan Demme', 'Crime, Drama, Thriller', 8.6),
  (24, 'Seven Samurai', 1954, 'Akira Kurosawa', 'Action, Adventure, Drama', 8.6),
  (25, 'The Pianist', 2002, 'Roman Polanski', 'Biography, Drama, Music', 8.5),
  (26, 'The Departed', 2006, 'Martin Scorsese', 'Crime, Drama, Thriller', 8.5),
  (27, 'Eternal Sunshine of the Spotless Mind', 2004, 'Michel Gondry', 'Drama, Romance, Sci-Fi', 8.3),
  (28, 'Raiders of the Lost Ark', 1981, 'Steven Spielberg', 'Action, Adventure', 8.4),
  (29, 'City of God', 2002, 'Fernando Meirelles, Kátia Lund', 'Crime, Drama', 8.6),
  (30, 'The Green Mile', 1999, 'Frank Darabont', 'Crime, Drama, Fantasy', 8.6),
  (31, 'Gladiator', 2000, 'Ridley Scott', 'Action, Adventure, Drama', 8.5),
  (32, 'Apocalypse Now', 1979, 'Francis Ford Coppola', 'Drama, Mystery, War', 8.4),
  (33, 'The Prestige', 2006, 'Christopher Nolan', 'Drama, Mystery, Sci-Fi', 8.5),
  (34, 'Memento', 2000, 'Christopher Nolan', 'Mystery, Thriller', 8.4),
  (35, 'The Shining', 1980, 'Stanley Kubrick', 'Drama, Horror', 8.4),
  (36, 'The Great Dictator', 1940, 'Charlie Chaplin', 'Comedy, Drama, War', 8.4),
  (37, 'The Usual Suspects', 1995, 'Bryan Singer', 'Crime, Mystery, Thriller', 8.5),
  (38, 'Amélie', 2001, 'Jean-Pierre Jeunet', 'Comedy, Romance', 8.3),
  (39, 'Blade Runner', 1982, 'Ridley Scott', 'Action, Sci-Fi, Thriller', 8.1),
  (40, 'Django Unchained', 2012, 'Quentin Tarantino', 'Drama, Western', 8.4);

INSERT INTO movies (id, title, year, director, genre, rating)
VALUES
  (41, 'The Dark Knight', 2008, 'Christopher Nolan', 'Action, Crime, Drama', 9.0),
  (42, 'The Lord of the Rings: The Return of the King', 2003, 'Peter Jackson', 'Adventure, Drama, Fantasy', 8.9),
  (43, 'Toy Story', 1995, 'John Lasseter', 'Animation, Adventure, Comedy', 8.3),
  (44, 'Braveheart', 1995, 'Mel Gibson', 'Biography, Drama, History', 8.3),
  (45, 'The Godfather: Part III', 1990, 'Francis Ford Coppola', 'Crime, Drama', 7.6),
  (46, 'The Empire Strikes Back', 1980, 'Irvin Kershner', 'Action, Adventure, Fantasy', 8.7),
  (47, 'Schindler''s List', 1993, 'Steven Spielberg', 'Biography, Drama, History', 8.9),
  (48, 'The Truman Show', 1998, 'Peter Weir', 'Comedy, Drama, Sci-Fi', 8.1),
  (49, 'The Social Network', 2010, 'David Fincher', 'Biography, Drama', 7.7),
  (50, 'The Sixth Sense', 1999, 'M. Night Shyamalan', 'Drama, Mystery, Thriller', 8.1),
  (51, 'The Breakfast Club', 1985, 'John Hughes', 'Comedy, Drama', 7.8),
  (52, 'Casino', 1995, 'Martin Scorsese', 'Crime, Drama', 8.2),
  (53, 'A Clockwork Orange', 1971, 'Stanley Kubrick', 'Crime, Drama, Sci-Fi', 8.3),
  (54, 'Reservoir Dogs', 1992, 'Quentin Tarantino', 'Crime, Drama, Thriller', 8.3),
  (55, 'The Green Mile', 1999, 'Frank Darabont', 'Crime, Drama, Fantasy', 8.6),
  (56, 'Gone Girl', 2014, 'David Fincher', 'Drama, Mystery, Thriller', 8.1),
  (57, 'No Country for Old Men', 2007, 'Joel Coen, Ethan Coen', 'Crime, Drama, Thriller', 8.1),
  (58, 'The Big Lebowski', 1998, 'Joel Coen, Ethan Coen', 'Comedy, Crime, Sport', 8.1),
  (59, 'Finding Nemo', 2003, 'Andrew Stanton, Lee Unkrich', 'Animation, Adventure, Comedy', 8.1),
  (60, 'The Godfather: Part II', 1974, 'Francis Ford Coppola', 'Crime, Drama', 9.0);

INSERT INTO movies (id, title, year, director, genre, rating)
VALUES
  (61, 'The Matrix', 1999, 'Lana Wachowski, Lilly Wachowski', 'Action, Sci-Fi', 8.7),
  (62, 'The Avengers', 2012, 'Joss Whedon', 'Action, Adventure, Sci-Fi', 8.0),
  (63, 'Interstellar', 2014, 'Christopher Nolan', 'Adventure, Drama, Sci-Fi', 8.6),
  (64, 'Whiplash', 2014, 'Damien Chazelle', 'Drama, Music', 8.5),
  (65, 'Gone with the Wind', 1939, 'Victor Fleming', 'Drama, History, Romance', 8.1),
  (66, 'Schindler''s List', 1993, 'Steven Spielberg', 'Biography, Drama, History', 8.9),
  (67, 'The Lord of the Rings: The Two Towers', 2002, 'Peter Jackson', 'Adventure, Drama, Fantasy', 8.7),
  (68, 'The Godfather: Part II', 1974, 'Francis Ford Coppola', 'Crime, Drama', 9.0),
  (69, 'The Shawshank Redemption', 1994, 'Frank Darabont', 'Drama', 9.3),
  (70, 'The Dark Knight Rises', 2012, 'Christopher Nolan', 'Action, Thriller', 8.4),
  (71, 'Goodfellas', 1990, 'Martin Scorsese', 'Biography, Crime, Drama', 8.7),
  (72, 'Inception', 2010, 'Christopher Nolan', 'Action, Adventure, Sci-Fi', 8.8),
  (73, 'Forrest Gump', 1994, 'Robert Zemeckis', 'Drama, Romance', 8.8),
  (74, 'The Silence of the Lambs', 1991, 'Jonathan Demme', 'Crime, Drama, Thriller', 8.6),
  (75, 'Seven Samurai', 1954, 'Akira Kurosawa', 'Action, Adventure, Drama', 8.6),
  (76, 'The Pianist', 2002, 'Roman Polanski', 'Biography, Drama, Music', 8.5),
  (77, 'The Departed', 2006, 'Martin Scorsese', 'Crime, Drama, Thriller', 8.5),
  (78, 'Eternal Sunshine of the Spotless Mind', 2004, 'Michel Gondry', 'Drama, Romance, Sci-Fi', 8.3),
  (79, 'Raiders of the Lost Ark', 1981, 'Steven Spielberg', 'Action, Adventure', 8.4),
  (80, 'City of God', 2002, 'Fernando Meirelles, Kátia Lund', 'Crime, Drama', 8.6),
  (81, 'The Green Mile', 1999, 'Frank Darabont', 'Crime, Drama, Fantasy', 8.6),
  (82, 'Gladiator', 2000, 'Ridley Scott', 'Action, Adventure, Drama', 8.5),
  (83, 'Apocalypse Now', 1979, 'Francis Ford Coppola', 'Drama, Mystery, War', 8.4),
  (84, 'The Prestige', 2006, 'Christopher Nolan', 'Drama, Mystery, Sci-Fi', 8.5),
  (85, 'Memento', 2000, 'Christopher Nolan', 'Mystery, Thriller', 8.4),
  (86, 'The Shining', 1980, 'Stanley Kubrick', 'Drama, Horror', 8.4),
  (87, 'The Great Dictator', 1940, 'Charlie Chaplin', 'Comedy, Drama, War', 8.4),
  (88, 'The Usual Suspects', 1995, 'Bryan Singer', 'Crime, Mystery, Thriller', 8.5),
  (89, 'Amélie', 2001, 'Jean-Pierre Jeunet', 'Comedy, Romance', 8.3),
  (90, 'Blade Runner', 1982, 'Ridley Scott', 'Action, Sci-Fi, Thriller', 8.1),
  (91, 'Django Unchained', 2012, 'Quentin Tarantino', 'Drama, Western', 8.4),
  (92, 'The Lion King', 1994, 'Roger Allers, Rob Minkoff', 'Animation, Adventure, Drama', 8.5),
  (93, 'Casablanca', 1942, 'Michael Curtiz', 'Drama, Romance, War', 8.5),
  (94, 'Schindler''s List', 1993, 'Steven Spielberg', 'Biography, Drama, History', 8.9),
  (95, 'The Shawshank Redemption', 1994, 'Frank Darabont', 'Drama', 9.3),
  (96, 'The Dark Knight Rises', 2012, 'Christopher Nolan', 'Action, Thriller', 8.4),
  (97, 'Goodfellas', 1990, 'Martin Scorsese', 'Biography, Crime, Drama', 8.7),
  (98, 'Inception', 2010, 'Christopher Nolan', 'Action, Adventure, Sci-Fi', 8.8),
  (99, 'Forrest Gump', 1994, 'Robert Zemeckis', 'Drama, Romance', 8.8),
  (100, 'The Matrix', 1999, 'Lana Wachowski, Lilly Wachowski', 'Action, Sci-Fi', 8.7),
  (101, 'The Avengers', 2012, 'Joss Whedon', 'Action, Adventure, Sci-Fi', 8.0),
  (102, 'Interstellar', 2014, 'Christopher Nolan', 'Adventure, Drama, Sci-Fi', 8.6),
  (103, 'Whiplash', 2014, 'Damien Chazelle', 'Drama, Music', 8.5),
  (104, 'Gone with the Wind', 1939, 'Victor Fleming', 'Drama, History, Romance', 8.1),
  (105, 'Schindler''s List', 1993, 'Steven Spielberg', 'Biography, Drama, History', 8.9),
  (106, 'The Lord of the Rings: The Two Towers', 2002, 'Peter Jackson', 'Adventure, Drama, Fantasy', 8.7),
  (107, 'The Godfather: Part II', 1974, 'Francis Ford Coppola', 'Crime, Drama', 9.0),
  (108, 'The Shawshank Redemption', 1994, 'Frank Darabont', 'Drama', 9.3),
  (109, 'The Dark Knight Rises', 2012, 'Christopher Nolan', 'Action, Thriller', 8.4),
  (110, 'Goodfellas', 1990, 'Martin Scorsese', 'Biography, Crime, Drama', 8.7),
  (111, 'Inception', 2010, 'Christopher Nolan', 'Action, Adventure, Sci-Fi', 8.8),
  (112, 'Forrest Gump', 1994, 'Robert Zemeckis', 'Drama, Romance', 8.8),
  (113, 'The Matrix', 1999, 'Lana Wachowski, Lilly Wachowski', 'Action, Sci-Fi', 8.7),
  (114, 'The Avengers', 2012, 'Joss Whedon', 'Action, Adventure, Sci-Fi', 8.0),
  (115, 'Interstellar', 2014, 'Christopher Nolan', 'Adventure, Drama, Sci-Fi', 8.6),
  (116, 'Whiplash', 2014, 'Damien Chazelle', 'Drama, Music', 8.5),
  (117, 'Gone with the Wind', 1939, 'Victor Fleming', 'Drama, History, Romance', 8.1),
  (118, 'Schindler''s List', 1993, 'Steven Spielberg', 'Biography, Drama, History', 8.9),
  (119, 'The Lord of the Rings: The Two Towers', 2002, 'Peter Jackson', 'Adventure, Drama, Fantasy', 8.7),
  (120, 'The Godfather: Part II', 1974, 'Francis Ford Coppola', 'Crime, Drama', 9.0),
  (121, 'The Shawshank Redemption', 1994, 'Frank Darabont', 'Drama', 9.3),
  (122, 'The Dark Knight Rises', 2012, 'Christopher Nolan', 'Action, Thriller', 8.4),
  (123, 'Goodfellas', 1990, 'Martin Scorsese', 'Biography, Crime, Drama', 8.7),
  (124, 'Inception', 2010, 'Christopher Nolan', 'Action, Adventure, Sci-Fi', 8.8),
  (125, 'Forrest Gump', 1994, 'Robert Zemeckis', 'Drama, Romance', 8.8),
  (126, 'The Matrix', 1999, 'Lana Wachowski, Lilly Wachowski', 'Action, Sci-Fi', 8.7),
  (127, 'The Avengers', 2012, 'Joss Whedon', 'Action, Adventure, Sci-Fi', 8.0),
  (128, 'Interstellar', 2014, 'Christopher Nolan', 'Adventure, Drama, Sci-Fi', 8.6),
  (129, 'Whiplash', 2014, 'Damien Chazelle', 'Drama, Music', 8.5),
  (130, 'Gone with the Wind', 1939, 'Victor Fleming', 'Drama, History, Romance', 8.1);